version: '3'

services:
  web-lighttpd:
    image: udfb/lighttpd-tcpdump

    volumes:
      - ./src/nginx/example_site:/var/www/localhost/htdocs
      - ./output/tcpdump:/tcpdump
    networks:
      web:
        aliases:
          - web-lighttpd.example.com
    ports:
      - "80:80"
    command: sh /script.sh

  http_crawler:
    image: udfb/http-generator
    depends_on:
            - web-nginx
    volumes:
      - ./output/http_client/log:/tmp
    networks:
      - web
    command: ["python", "run.py", "-p", "http://web-lighttpd.example.com"]
    deploy:
      mode: replicated
      replicas: 5

  slowloris:
    image: udfb/slowloris
    depends_on:
            - web-nginx
    networks:
      - web
    command: ["slowloris", "web-lighttpd.example.com"]
    deploy:
      mode: replicated
      replicas: 0

networks:
  web: