version: '3'

services:
  # service available via http://web-nginx
  web_nginx:
    image: nginx
    container_name: web_nginx
    volumes:
      - ./src/nginx/mysite.template:/etc/nginx/conf.d/mysite.template
      - ./src/nginx/example_site:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "service:web_nginx"
    depends_on:
            - web_nginx
    volumes:
      - ./output/tcpdump:/tcpdump
    command: [ "-C", "100", "-W", "2", "-v", "-i", "any", "-w", "/tcpdump/myapp.pcap" ]


#  http_crawler:
#    build: ../http_client
#    volumes:
#      - ../src/http_client:/usr/src/app
