version: '3'

services:
  smb_client:
    container_name: smb_client
    hostname: smb_clinet
    build:
      context: ../../src/smb/client
    env_file:
      - credentials.env
    command: ["python", "crawler_client.py", "-t", "usual", "-n", "max"]
    deploy:
      mode: replicated
      replicas: 1