version: '3'

services:
  web-nginx:
    image: udfb/nginx-tcpdump
    hostname: web-nginx.example.com
    volumes:
      - ../../src/nginx/example_site:/usr/share/nginx/html
      - ../../output/tcpdump:/tcpdump
    networks:
      web:
        aliases:
          - web-nginx.example.com
    ports:
      - "80:80"
    command: sh /script.sh


  http_crawler:
    image: udfb/http-generator
    depends_on:
      - web-nginx
    volumes:
      - ../../output/http_client/log:/tmp
    networks:
      - web
    command: ["python", "run.py", "-p", "http://web-nginx.example.com"]
    deploy:
      mode: replicated
      replicas: 1

  sql_map:
    hostname: sql_map
    image: udfb/sql_map
    depends_on:
      - web-nginx
    networks:
      - web
    command: ["python", "sqlmap.py", "-u", "http://web-nginx.example.com/login.html?user=uzivatel&password=heslo", "--batch"]
    deploy:
      mode: replicated
      replicas: 1


networks:
  web: